version: '3.7'
services:
    sugpa-web:
        build: .
        image: sugpa-web
        environment:
            - HOST=sugpa-mysql
            - DB=sugpa
            - USER=agente
            - PASSWORD=agente
            - DBPORT=3306
        ports:
            - "8080:8080"
        depends_on:
            - sugpa-mysql
        networks:
            - monolito       
    sugpa-mysql:
     extends:
        file: mysql.yml
        service: sugpa-mysql

networks:
  monolito: {}