version: '3.7'
services:
  sugpa-mysql:
    image: mysql:8.0.20
    environment:
      - MYSQL_DATABASE=sugpa
      - MYSQL_USER=agente
      - MYSQL_PASSWORD=agente
      - MYSQL_ROOT_PASSWORD=agente
    ports:
      - 3306:3306
    networks:
      - monolito
    volumes:
      - "./src/main/resources/db/bdrio_vehiculos_25-09.sql:/docker-entrypoint-initdb.d/bdrio_vehiculos_25-09.sql"      
    command: --default-authentication-plugin=mysql_native_password

networks:
  monolito: {}