
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `bdrio`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE `vehiculos` (
  `REGISTRO` VARCHAR(4) NOT NULL,
  `PLAYA_ING` VARCHAR(40) NULL DEFAULT NULL,
  `FECHA_ING` DATETIME NULL DEFAULT NULL,
  `HORA_ING` VARCHAR(8) NULL DEFAULT NULL,
  `TIPO` VARCHAR(20) NULL DEFAULT NULL,
  `TIPO_DOMINIO` VARCHAR(40) NULL DEFAULT NULL,
  `DOMINIO` VARCHAR(8) NULL DEFAULT NULL,
  `MARCA` VARCHAR(10) NULL DEFAULT NULL,
  `MODELO` VARCHAR(11) NULL DEFAULT NULL,
  `COLOR` VARCHAR(20) NULL DEFAULT NULL,
  `MOTIVO` VARCHAR(15) NULL DEFAULT NULL,
  `NCHASIS_NMOTOR` VARCHAR(54) NULL DEFAULT NULL,
  `ACTA_CONTRAVENCIONAL` VARCHAR(8) NULL DEFAULT NULL,
  `ACTA_DE_COMPROBACION` VARCHAR(17) NULL DEFAULT NULL,
  `ACTA_Z` VARCHAR(10) NULL DEFAULT NULL,
  `AGENTE_LABRANTE` VARCHAR(50) NULL DEFAULT NULL,
  `NOMBRE_INFRACTOR` VARCHAR(60) NULL DEFAULT NULL,
  `TIPODOC` VARCHAR(20) NULL DEFAULT NULL,
  `NDOC` VARCHAR(15) NULL DEFAULT NULL,
  `CHOFER_DNI` VARCHAR(27) NULL DEFAULT NULL,
  `CALLE` VARCHAR(67) NULL DEFAULT NULL,
  `NUMERO` VARCHAR(10) NULL DEFAULT NULL,
  `ENTRECALLE1` VARCHAR(60) NULL DEFAULT NULL,
  `ENTRECALLE2` VARCHAR(60) NULL DEFAULT NULL,
  `REFERENCIA_LUGAR` VARCHAR(70) NULL DEFAULT NULL,
  `OBSERVACIONES` VARCHAR(70) NULL DEFAULT NULL,
  `AGENTE_DE_PLAYA` VARCHAR(12) NULL DEFAULT NULL,
  `INVENTARIO` VARCHAR(3) NULL DEFAULT NULL,
  `FECHA_EGR` DATETIME NULL DEFAULT NULL,
  `HORA_EGR` VARCHAR(8) NULL DEFAULT NULL,
  `PERSONA_Q_RETIRO` VARCHAR(89) NULL DEFAULT NULL,
  `ENTREGA_AGENTE` VARCHAR(12) NULL DEFAULT NULL,
  `NOTAS` VARCHAR(105) NULL DEFAULT NULL,
  `CONTROL_DE_LEGALES` VARCHAR(3) NULL DEFAULT NULL,
  `TRASLADO_A_COMPACTACION` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`REGISTRO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
