<script>
	var infracciones = [{ text: '7063 - Acompañante (MOTO) supera el límite alcohol en sangre', value: '7063'}, 
						{ text: '7062 - Negarse Ctrl ALCOHOLEMIA /Estupef. / otra sustancia (Conductor vehíc/moto o acompañante)', value: '7062'},
						{ text: '6187 - Negarse Ctrl ALCOHOLEMIA / Estupef. / otra sustancia (Taxi/Tte. Escolar, Pasajeros/Remises - en servicio)', value: '6187'},
						{ text: '8910 - Cruzar BARRERA FFCC baja (Particulares)', value: '8910'},
						{ text: '8911 - Cruzar BARRERA FFCC baja (Tte Escolar/Pasajeros/Carga)', value: '8911'},
						{ text: '6660 - Evadir pago estación de PEAJE en Autopista', value: '6660'},
						{ text: '6762 - Circular (Moto) x Ciclovía a CONTRAMANO en contracarril', value: '6762'},
						{ text: '6560 - Circular en sentido contrario (en vías doble circulación)', value: '6560'},
						{ text: '6780 - Circular x Artería peatonal / Zona carril (prohib- exclusivo- preferencial), o excede límite (dimensión/peso/potencia) permitida para la vía transitada', value: '6780'},
						{ text: '6761 - Circular por carril del STR utilizado por el METROBÚS', value: '6761'},
						{ text: '6167 - Obstruir vía carril exclusivo/Preferencial/Metrobús/Premetro', value: '6167'},
						{ text: '6680 - Obstruir vía Transversal/Ciclovía/Vereda/Rampa Discapac. /Estacionamiento reservado', value: '6680'},
						{ text: '6490 - Manipular CELULAR/Utilizar AURICULARES/reproductor VIDEO', value: '6490'},
						{ text: '6492 - Redactar o enviar MENSAJE DE TEXTO', value: '6492'},
						{ text: '6540 - Circular (VEHICULO) a CONTRAMANO', value: '6540'},
						{ text: '6640 - Circular MARCHA ATRÁS en forma indebida y sin justificación', value: '6640'},
						{ text: '6600 - GIRAR en "U" o hacia transversal en forma antirreglamentaria', value: '6600'},
						{ text: '6620 - No respetar (PRIORIDAD PASO en BOCACALLE/cartel "PARE")', value: '6620'},
						{ text: '6580 - No respetar carriles/ No advertir maniobras/ Conducta temeraria, maliciosa o imprudente', value: '6580'},
						{ text: '6191 - No CONTAR con SEGURO obligatorio VIGENTE (cod.6191)', value: '6191'},
						{ text: '6161 - No exhibir CÉDULA VERDE o CÉDULA AZUL', value: '6161'},
						{ text: '6190 - No PORTAR cobertura, PÓLIZA o TARJETA seguro VIGENTE)', value: '6190'},
						{ text: '7064 - Utilizar cartel/credencial/patente/docum. Acredite FRANQUICIA de tránsito/estaciona. Inexistente/antirreglam. o no aplicable a persona que lo utiliza/exhibe', value: '7064'},
						{ text: '6960 - Enseñar a conducir vehíc. en lugar no habilitado (Academia) ', value: '6960'},
						{ text: '6950 - Enseñar a conducir vehíc. en lugar no habilitado (Particular) ', value: '6950'},
						{ text: '6920 - Estacionamiento TARIFADO/MEDIDO vencido', value: '6920'},
						{ text: '6910 - Estacionar LUGAR RESERVADO (Serv.EMERG. / PARADA Tte.Pasaj/ Vehíc. Persona discapac./ RAMPA discapac./ ENTRADA vehíc./ CICLOVÍA/ CARRIL exclusivo/ corredor METROBUS/ zona Micro-Macrocentro)', value: '6910'},
						{ text: '6935 - Estac. en ARTERIA PEATONAL, sobre ACERA o parte de de ella', value: '6935'},
						{ text: '6900 - Estac. en lugar prohibido o en forma antirreglamentaria', value: '6900'},
						{ text: '6890 - CARGA/DESCARGA fuera de hora, o en lugar prohibido (Respon. VEHÍCULO)', value: '6890'},
						{ text: '6185 - CARGA/DESCARGA fuera de hora, o en lugar prohibido (Respon./Propietario COMERCIO)', value: '6185'},
						{ text: '7045 - Vehíc. LIMITA/OBSTRUYE estacionamiento y/o circulación x colocación transitoria de un elemento/dispositivo', value: '7045'},
						{ text: '6980 - No respetar indicaciones de agente que dirige el tránsito', value: '6980'},
						{ text: '6130 - Conducir sin ANTEOJOS/LENTES contacto indicado en Licencia', value: '6130'},
						{ text: '6105 - FALTA de Licencia y/o documentación habilitante de chofer y/o esté INHABILITADO para conducir (Tte. Público)', value: '6105'},
						{ text: '6122 - Licencia/documentación habilitante VENCIDA (Tte. Público)', value: '6122'},
						{ text: '6120 - Licencia VENCIDA o caduca', value: '6120'},
						{ text: '6100 - NO PORTAR licencia', value: '6100'},
						{ text: '6140 - No portar licencia que habilita conducir CATEGORÍA vehíc.', value: '6140'},
						{ text: '6862 - NO POSEER licencia', value: '6862'},
						{ text: '6110 - Permitir conducir sin licencia / doc. habilitante de chofer / inhabilitado para conducir (Tte. Público) ', value: '6110'},
						{ text: '6121 - Permitir conducir con Licencia o doc. vencida (Empresa Tte, titular, mandataria o Respons.) ', value: '6121'},
						{ text: '6150 - Permitir conducir vehíc. sin licencia que habilita CATEGORÍA del vehíc. (titular o empresa) ', value: '6150'},
						{ text: '7065 - Circular SIN LUCES encendidas en arteria obligatoria / Utilizar LUCES ALTAS cuando no está permitido', value: '7065'},
						{ text: '7066 - Utilizar LUCES no reglamentarias o que induzcan a error', value: '7066'},
						{ text: '7050 - Violar LUZ ROJA', value: '7050'},
						{ text: '6186 - Violar LUZ ROJA (Taxi / Tte Escolar Pasajeros / Remise)', value: '6186'},
						{ text: '7021 - (BICICLETAS) Circular ASIDO a otro vehíc. o apareado detrás/No usar CASCO/ Falta espejo, luces / Transportar persona en diseño vehíc. no apto / No respetar señalización vial  ', value: '7021'},
						{ text: '7010 - Circular sin ANTIPARRAS (MOTO/ MOTONETA/ CICLOM. sin parabrisas)', value: '7010'},
						{ text: '7001 - (MOTO) Circular ASIDO a otro vehíc. o apareado detrás/ No usar CASCO / Transportar persona en diseño vehíc. no apto / Transportar MENORES de 16 años', value: '7001'},
						{ text: '6970 - (PEATON) - CRUZAR calzada x lugar no habilitado/no respetar SEMÁFORO que permita el cruce', value: '6970'},
						{ text: '6886 - Circular por arteria no permitida o sin DISTINTIVO', value: '6886'},
						{ text: '6230 - Circular con ANTIRADAR o ANTIFOTO', value: '6230'},
						{ text: '6430 - Circular c/VIDRIOS TONALIZADOS impide distinguir ocupantes', value: '6430'},
						{ text: '6450 - Circular sin ESPEJO retrovisor o c/objeto dificulta visión vidrio trasero/laterales (Vehíc.)', value: '6450'},
						{ text: '6470 - Circular SIN TAPA tanque de COMBUSTIBLE', value: '6470'},
						{ text: '8885 - Colocar/Instalar parada Tte. o señal/símbolo de tránsito sin autorización // Retirar, trasladar, ocultar, modificar, deteriorar o destruir cualquier SEÑALIZACIÓN VIAL ', value: '8885'},
						{ text: '8884 - Dificultar circulación vehíc. o no señalizar (Respons OBRA)', value: '8884'},
						{ text: '6250 - FALTA de (FRENOS, LUCES, CINTURÓN / otro elem. seguridad) o Deficiente', value: '6250'},
						{ text: '6410 - Falta de PARAGOLPES', value: '6410'},
						{ text: '6290 - Falta dispositivo control de GASES o con Deficiencias', value: '6290'},
						{ text: '6280 - Falta LIMITADOR de velocidad', value: '6280'},
						{ text: '6330 - Falta SILENCIADOR o Deficiente/Alterado o c/salida total/parcial directa de gases', value: '6330'},
						{ text: '6271 - MENOR de 4 años en ASIENTO TRASERO sin acompañante adulto o SIN DISPOSITIVO retención infantil', value: '6271'},
						{ text: '6501 - MENOR en ASIENTO DELANTERO o de menor talla', value: '6501'},
						{ text: '6700 - No CEDER PASO a Policía/Bomb/Ambul/Serv. Urgencia', value: '6700'},
						{ text: '6270 - NO USAR CINTURÓN de seguridad', value: '6270'},
						{ text: '6160 - Permitir/Ceder manejo de vehíc. persona sin edad necesaria', value: '6160'},
						{ text: '6370 - Tener BOCINA o SIRENA antirreglamentarias', value: '6370'},
						{ text: '6390 - Tener PARAGOLPES antirreglamentarios', value: '6390'},
						{ text: '6800 - Transportar MAYOR nro. PERSONAS s/CAPACIDAD vehíc.', value: '6800'},
						{ text: '6350 - Usar en forma indebida la BOCINA', value: '6350'},
						{ text: '6310 - Verter COMBUSTIBLE/ Agua servida/ ARROJAR OBJETO o RESIDUO hacia el exterior del vehíc.', value: '6310'},
						{ text: '6720 - Interrumpir FILAS ESCOLARES', value: '6720'},
						{ text: '6740 - No respetar SENDA PEATONAL o PRIORIDAD PASO del peatón', value: '6740'},
						{ text: '8919 - Asignar viaje Radiotaxi sin autorización', value: '8919'},
						{ text: '8920 - Asignar viaje Radiotaxi sin Licencia de taxi (persona)', value: '8920'},
						{ text: '8921 - Asignar viaje Radiotaxi sin Licencia taxi (Titu/Chofer/Respons)', value: '8921'},
						{ text: '8915 - Asignar viaje x vía telef., mail, otros y no x Central Radio Taxi', value: '8915'},
						{ text: '8933 - Cobrar distinta cant.fichas o adicional a Discapac.', value: '8933'},
						{ text: '6876 - Cobrar por sobre/debajo VALOR TARIFA que fija GCBA', value: '6876'},
						{ text: '8938 - Emplear equipo comunicación no homologado (Titu/Respons)', value: '8938'},
						{ text: '8935 - Exhibir cartel Radio Taxi sin alta Empresa (Emp/Respon/Chofer)', value: '8935'},
						{ text: '8934 - Exhibir cartel Radio Taxi sin equip.radio (Emp/Respon/Chofer)', value: '8934'},
						{ text: '6872 - Incumplir obligac. SEC.COMU./Autoriz.anual VENCIDA/No cumplir requisitos s/norma vigte', value: '6872'},
						{ text: '6182 - Negarse detener mecan./dispos.electr. PUBLICIDAD INTERIOR', value: '6182'},
						{ text: '6181 - Negarse s/justific. transportar pasajero que solicita servicio', value: '6181'},
						{ text: '6183 - No portar FICHA IDENTIFICAC.Titu.licencia/chofer o Cartel VALOR de TARIFA', value: '6183'},
						{ text: '7552 - Poseer dispo.mecánico/electrónico que incrementa tarifa', value: '7552'},
						{ text: '6871 - Prestar serv. SIN HABILITAC./ Con identificac. taxi sin poseer licencia/ Realizar actividad clandestina (Titu/Respons/Mandat)', value: '6871'},
						{ text: '8940 - Prestar serv. con autorizac. radioelect. anual vencida + de 30 días (Titu/Respons)', value: '8940'},
						{ text: '8936 - Prestar serv. con baja de Empresa y con señal Radio Taxi (Titu/Respons)', value: '8936'},
						{ text: '8937 - Prestar serv. Radio Taxi sin estar abonado a empresa habilitada (Titu/Respons/Chofer)', value: '8937'},
						{ text: '8939 - Prestar serv. Radio Taxi sin verificar/registrar en Autoridad la instalac/función equipo radio', value: '8939'},
						{ text: '6874 - Radio Taxi con IRA VENCIDO y/o está de baja y no elimina señales que lo identificaban', value: '6874'},
						{ text: '6873 - Radio Taxi NO ABONADO a estac.central o DIFIERE estac.central a la abonada', value: '6873'},
						{ text: '6875 - Realizar promo./Cobrar TARIFA NO AUTORIZADA (Titu/Empr/Mandatario)', value: '6875'},
						{ text: '8928 - Empresa RT c/trabajador que no cumple registración s/ley laboral', value: '8928'},
						{ text: '8932 - Empresa RT tiene abonados sin tener equipo de radio', value: '8932'},
						{ text: '8924 - Empresa RT incumple autorización funcionamiento', value: '8924'},
						{ text: '8917 - Empresa RT Habilitación vencida (entre 181 y 360 días)', value: '8917'},
						{ text: '8916 - Empresa RT Habilitación vencida (entre 30 y 180 días)', value: '8916'},
						{ text: '8918 - Empresa RT Habilitación vencida (más de 360 días)', value: '8918'},
						{ text: '8929 - Empresa RT no comunica cambio de localización Estac.Central', value: '8929'},
						{ text: '8925 - Empresa RT no comunica detalle de abonados', value: '8925'},
						{ text: '8927 - Empresa RT no cumplimenta previsión s/Cod. TyT', value: '8927'},
						{ text: '8930 - Empresa RT no opera las 24 horas s/Cod. TyT', value: '8930'},
						{ text: '8931 - Empresa RT opera con + de una Estación Central', value: '8931'},
						{ text: '8922 - Empresa RT presta serv. a Radio Taxi que no cumple norma legal ', value: '8922'},
						{ text: '8926 - Empresa RT presta serv. c/menor cant. de abonados s/Cod. TyT', value: '8926'},
						{ text: '8923 - Empresa RT realiza promoción no autorizada', value: '8923'},
						{ text: '8914 - Empresa RT sin habilitación', value: '8914'},
						{ text: '6169 - Dañar/alterar/retirar DISPOSITIVO de ALCOHOLEMIA (CONDUCTOR Vehíc. Tte Escolares)', value: '6169'},
						{ text: '6168 - Dañar/alterar/retirar DISPOSITIVO de ALCOHOLEMIA (TITULAR o Respons. Vehíc. Tte. Escolares)', value: '6168'},
						{ text: '6184 - Exceder PESO MÁXIMO establecido por EJE (Tte CARGA)', value: '6184'},
						{ text: '6870 - No cumplir norma regula requisito vehíc. habilitado para prestar servicio o en infracción a habilitación concedida', value: '6870'},
						{ text: '7030 - No cumplir norma regula servicio (Tte PRIVADO Pasajeros o ALQUILER de Autos sin conductor)', value: '7030'},
						{ text: '6840 - No cumplir norma uso radio/reproduc. sonido o publicidad interior-ext/TRATO al pasajero/prohib.FUMAR (Tte. Pasajero)', value: '6840'},
						{ text: '6850 - No cumplir HORARIO servicio / VESTIMENTA (Tte. Pasajeros)', value: '6850'},
						{ text: '6877 - No poseer HABILITACIÓN para prestar servicio (Respons. vehíc. Tte CARGA o Pasajeros)', value: '6877'},
						{ text: '6820 - No poseer PARADA ASC_DESC/no ARRIMAR a acera/circular PUERTA ABIERTA', value: '6820'},
						{ text: '6830 - Permitir ocupar LUGAR NO DESTINADO a viajar en ellos', value: '6830'},
						{ text: '6880 - Transporta carga s/permiso s/PESO/DIMENSIÓN, tener permiso y violar límite autorización/ CARGA DESCUBIERTA o no asegurada (Tte Carga)', value: '6880'},
						{ text: '6881 - Transporta carga s/permiso s/PESO/DIMENSIÓN, tener permiso y violar límite autorización/ CARGA DESCUBIERTA o no aseguradate (Tte Explosivos /objetos inflamables -volátiles -insalubres/animales)', value: '6881'},
						{ text: '6180 - No exhibir documentac. para Tte.Sust.PELIGROSA (Tte CARGA)', value: '6180'},
						{ text: '6166 - Transportar Sust. ALIMENTICIAS sin habilitación', value: '6166'},
						{ text: '6670 - Transportar Sust. PELIGROSA infringe norma regulan actividad', value: '6670'},
						{ text: '6165 - Transportar Sust. PELIGROSA sin habilitación', value: '6165'},
						{ text: '6241 - VTV VENCIDA/ sin realizar verificación (Vehíc/Moto)', value: '6241'},
						{ text: '6240 - No PORTAR certificado VERIFIC. Técnica (Vehíc/Moto)', value: '6240'},
						{ text: '6242 - No realizar Grabado de AUTOPARTES', value: '6242'},
						{ text: '6243 - Incumplir Grabado AUTOPARTES (Gestor/ Mandat/Concesión /Intermediario)', value: '6243'},
						{ text: '6780 - Prohibición circular según DÍA/HORA/CARACTERÍSTICA vehíc.	', value: '6780'}];
</script>